version: '3.8'

services:

  mongodb:
      image: mongo:latest
      ports:
        - '27017:27017'
      volumes:
        - mongo_db:/data/db
      networks:
        - project-network

volumes:
  mongo_db:

networks:
  project-network:
    driver: bridge