// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from '@hey-api/client-axios'
import {
  type GetMovieData,
  type GetMovieError,
  type GetMovieResponse,
  GetMovieResponseTransformer,
} from './types.gen'

export const client = createClient(createConfig())

/**
 * Get All Movies
 */
export const getMovie = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<GetMovieData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    GetMovieResponse,
    GetMovieError,
    ThrowOnError
  >({
    ...options,
    url: '/api/v1/movie/all',
    responseTransformer: GetMovieResponseTransformer,
  })
}
