// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type MovieRequestSchema = {
  limit?: number | null
  offset?: number | null
}

export type MovieSchema = {
  id: number
  name: string
  title: string
  image?: string | null
  afisha_image?: string | null
  create_time: Date
  update_time: Date
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type GetMovieData = {
  body?: MovieRequestSchema | null
}

export type GetMovieResponse = Array<MovieSchema>

export type GetMovieError = HTTPValidationError

export type GetMovieResponseTransformer = (
  data: any
) => Promise<GetMovieResponse>

export type MovieSchemaModelResponseTransformer = (data: any) => MovieSchema

export const MovieSchemaModelResponseTransformer: MovieSchemaModelResponseTransformer =
  (data) => {
    if (data?.create_time) {
      data.create_time = new Date(data.create_time)
    }
    if (data?.update_time) {
      data.update_time = new Date(data.update_time)
    }
    return data
  }

export const GetMovieResponseTransformer: GetMovieResponseTransformer = async (
  data
) => {
  if (Array.isArray(data)) {
    data.forEach(MovieSchemaModelResponseTransformer)
  }
  return data
}
